services:
  web:
    build: ./mis
    container_name: mis_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mis:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mis_db
    environment:
      POSTGRES_DB: medical_information_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: