# Generated by Django 5.2.5 on 2025-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(null=True, related_name='doctors', to='app.clinic'),
        ),
    ]
