# Generated by Django 5.2.5 on 2025-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doctor_clinics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(related_name='doctors', to='app.clinic'),
        ),
    ]
